texto = input("Introduce una cadena de texto: ")
print("Longitud de la cadena: ", len(texto))
print("Texto en capitals: ", texto.capitalize())
print("Texto en mayúscula: ", texto.upper())
print("Texto en minúscula: ", texto.lower())
print("Swapcase: ", texto.swapcase())
print("---------------------------------------")
print("Cambio 'a' por 'o': ", texto.replace('e','o'))
print("Troceo por espacios: ", texto.split(' '))
